name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
   

    # Set up SSH for deployment
    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}

    # Deploy to your EC2 instance (replace with your specific commands)
    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-60-217-178.eu-north-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/fastapi-book-project
          sudo git fetch origin main
          sudo git reset --hard origin/main
          docker build -t fastapi-app .
          docker stop fastapi-container || true
          docker rm fastapi-container || true
          docker run -d --name fastapi-container -p 8000:8000 fastapi-app
        
        EOF
