name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
   

    # Set up SSH for deployment
    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }
        HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}}

    # Deploy to your EC2 instance (replace with your specific commands)
    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-60-205-28.eu-north-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          source myenv/bin/activate
          pip install -r requirements.txt
           sudo service fastapi restart
          sudo service nginx restart
        EOF
