name: Test FastAPI Project

on:
  push:
    branches:
      - main


#on: 
  #pull_request:
    #branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze  

      # Step 4: Run tests
      - name: Run pytest
        run: |
          source myenv/bin/activate
          pytest --maxfail=5 --disable-warnings -v
